/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppOportunidadesRouteImport } from './routes/app.oportunidades'
import { Route as AppImportarRouteImport } from './routes/app.importar'
import { Route as AppDiagnosticoRouteImport } from './routes/app.diagnostico'
import { Route as AppConversasRouteImport } from './routes/app.conversas'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCobrancasRouteImport } from './routes/app.cobrancas'
import { Route as AppCampanhasRouteImport } from './routes/app.campanhas'
import { Route as AppAvaliacoesRouteImport } from './routes/app.avaliacoes'
import { Route as AppAutomacoesRouteImport } from './routes/app.automacoes'
import { Route as AppAtividadeRouteImport } from './routes/app.atividade'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as ApiWebhooksMetaLeadsRouteImport } from './routes/api/webhooks/meta-leads'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksZapiReceiveRouteImport } from './routes/api/webhooks/zapi-receive'
import { Route as ApiWebhooksZapiStatusRouteImport } from './routes/api/webhooks/zapi-status'
import { Route as ApiWebhooksZapiDisconnectRouteImport } from './routes/api/webhooks/zapi-disconnect'
import { Route as ApiWebhooksZapiConnectRouteImport } from './routes/api/webhooks/zapi-connect'
import { Route as ApiWebhooksMetaMessagesRouteImport } from './routes/api/webhooks/meta-messages'
import { Route as ApiWebhooksMetaCommentsRouteImport } from './routes/api/webhooks/meta-comments'
import { Route as ApiCronCsTouchpointsRouteImport } from './routes/api/cron/cs-touchpoints'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesRoute = AppOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticoRoute = AppDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AppRoute,
} as any)
const AppConversasRoute = AppConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCobrancasRoute = AppCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesRoute = AppAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadeRoute = AppAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMetaLeadsRoute = ApiWebhooksMetaLeadsRouteImport.update({
  id: '/api/webhooks/meta-leads',
  path: '/api/webhooks/meta-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksZapiReceiveRoute = ApiWebhooksZapiReceiveRouteImport.update({
  id: '/api/webhooks/zapi-receive',
  path: '/api/webhooks/zapi-receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksZapiStatusRoute = ApiWebhooksZapiStatusRouteImport.update({
  id: '/api/webhooks/zapi-status',
  path: '/api/webhooks/zapi-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksZapiDisconnectRoute = ApiWebhooksZapiDisconnectRouteImport.update({
  id: '/api/webhooks/zapi-disconnect',
  path: '/api/webhooks/zapi-disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksZapiConnectRoute = ApiWebhooksZapiConnectRouteImport.update({
  id: '/api/webhooks/zapi-connect',
  path: '/api/webhooks/zapi-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMetaMessagesRoute = ApiWebhooksMetaMessagesRouteImport.update({
  id: '/api/webhooks/meta-messages',
  path: '/api/webhooks/meta-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMetaCommentsRoute = ApiWebhooksMetaCommentsRouteImport.update({
  id: '/api/webhooks/meta-comments',
  path: '/api/webhooks/meta-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCsTouchpointsRoute = ApiCronCsTouchpointsRouteImport.update({
  id: '/api/cron/cs-touchpoints',
  path: '/api/cron/cs-touchpoints',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/cobrancas': typeof AppCobrancasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/importar': typeof AppImportarRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/p/$token': typeof PTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/zapi-receive': typeof ApiWebhooksZapiReceiveRoute
  '/api/webhooks/zapi-status': typeof ApiWebhooksZapiStatusRoute
  '/api/webhooks/zapi-disconnect': typeof ApiWebhooksZapiDisconnectRoute
  '/api/webhooks/zapi-connect': typeof ApiWebhooksZapiConnectRoute
  '/api/webhooks/meta-messages': typeof ApiWebhooksMetaMessagesRoute
  '/api/webhooks/meta-comments': typeof ApiWebhooksMetaCommentsRoute
  '/api/cron/cs-touchpoints': typeof ApiCronCsTouchpointsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/cobrancas': typeof AppCobrancasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/importar': typeof AppImportarRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/p/$token': typeof PTokenRoute
  '/app': typeof AppIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/zapi-receive': typeof ApiWebhooksZapiReceiveRoute
  '/api/webhooks/zapi-status': typeof ApiWebhooksZapiStatusRoute
  '/api/webhooks/zapi-disconnect': typeof ApiWebhooksZapiDisconnectRoute
  '/api/webhooks/zapi-connect': typeof ApiWebhooksZapiConnectRoute
  '/api/webhooks/meta-messages': typeof ApiWebhooksMetaMessagesRoute
  '/api/webhooks/meta-comments': typeof ApiWebhooksMetaCommentsRoute
  '/api/cron/cs-touchpoints': typeof ApiCronCsTouchpointsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/atividade': typeof AppAtividadeRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/avaliacoes': typeof AppAvaliacoesRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/cobrancas': typeof AppCobrancasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/conversas': typeof AppConversasRoute
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/importar': typeof AppImportarRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/pacientes': typeof AppPacientesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/p/$token': typeof PTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/zapi-receive': typeof ApiWebhooksZapiReceiveRoute
  '/api/webhooks/zapi-status': typeof ApiWebhooksZapiStatusRoute
  '/api/webhooks/zapi-disconnect': typeof ApiWebhooksZapiDisconnectRoute
  '/api/webhooks/zapi-connect': typeof ApiWebhooksZapiConnectRoute
  '/api/webhooks/meta-messages': typeof ApiWebhooksMetaMessagesRoute
  '/api/webhooks/meta-comments': typeof ApiWebhooksMetaCommentsRoute
  '/api/cron/cs-touchpoints': typeof ApiCronCsTouchpointsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/atividade'
    | '/app/automacoes'
    | '/app/avaliacoes'
    | '/app/campanhas'
    | '/app/cobrancas'
    | '/app/configuracoes'
    | '/app/conversas'
    | '/app/diagnostico'
    | '/app/importar'
    | '/app/oportunidades'
    | '/app/pacientes'
    | '/app/relatorios'
    | '/p/$token'
    | '/app/'
    | '/api/public/google/callback'
    | '/api/webhooks/meta-leads'
    | '/api/webhooks/stripe'
    | '/api/webhooks/zapi-receive'
    | '/api/webhooks/zapi-status'
    | '/api/webhooks/zapi-disconnect'
    | '/api/webhooks/zapi-connect'
    | '/api/webhooks/meta-messages'
    | '/api/webhooks/meta-comments'
    | '/api/cron/cs-touchpoints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/atividade'
    | '/app/automacoes'
    | '/app/avaliacoes'
    | '/app/campanhas'
    | '/app/cobrancas'
    | '/app/configuracoes'
    | '/app/conversas'
    | '/app/diagnostico'
    | '/app/importar'
    | '/app/oportunidades'
    | '/app/pacientes'
    | '/app/relatorios'
    | '/p/$token'
    | '/app'
    | '/api/public/google/callback'
    | '/api/webhooks/meta-leads'
    | '/api/webhooks/stripe'
    | '/api/webhooks/zapi-receive'
    | '/api/webhooks/zapi-status'
    | '/api/webhooks/zapi-disconnect'
    | '/api/webhooks/zapi-connect'
    | '/api/webhooks/meta-messages'
    | '/api/webhooks/meta-comments'
    | '/api/cron/cs-touchpoints'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/atividade'
    | '/app/automacoes'
    | '/app/avaliacoes'
    | '/app/campanhas'
    | '/app/cobrancas'
    | '/app/configuracoes'
    | '/app/conversas'
    | '/app/diagnostico'
    | '/app/importar'
    | '/app/oportunidades'
    | '/app/pacientes'
    | '/app/relatorios'
    | '/p/$token'
    | '/app/'
    | '/api/public/google/callback'
    | '/api/webhooks/meta-leads'
    | '/api/webhooks/stripe'
    | '/api/webhooks/zapi-receive'
    | '/api/webhooks/zapi-status'
    | '/api/webhooks/zapi-disconnect'
    | '/api/webhooks/zapi-connect'
    | '/api/webhooks/meta-messages'
    | '/api/webhooks/meta-comments'
    | '/api/cron/cs-touchpoints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PTokenRoute: typeof PTokenRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiWebhooksMetaLeadsRoute: typeof ApiWebhooksMetaLeadsRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiWebhooksZapiReceiveRoute: typeof ApiWebhooksZapiReceiveRoute
  ApiWebhooksZapiStatusRoute: typeof ApiWebhooksZapiStatusRoute
  ApiWebhooksZapiDisconnectRoute: typeof ApiWebhooksZapiDisconnectRoute
  ApiWebhooksZapiConnectRoute: typeof ApiWebhooksZapiConnectRoute
  ApiWebhooksMetaMessagesRoute: typeof ApiWebhooksMetaMessagesRoute
  ApiWebhooksMetaCommentsRoute: typeof ApiWebhooksMetaCommentsRoute
  ApiCronCsTouchpointsRoute: typeof ApiCronCsTouchpointsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/oportunidades': {
      id: '/app/oportunidades'
      path: '/oportunidades'
      fullPath: '/app/oportunidades'
      preLoaderRoute: typeof AppOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/importar': {
      id: '/app/importar'
      path: '/importar'
      fullPath: '/app/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnostico': {
      id: '/app/diagnostico'
      path: '/diagnostico'
      fullPath: '/app/diagnostico'
      preLoaderRoute: typeof AppDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversas': {
      id: '/app/conversas'
      path: '/conversas'
      fullPath: '/app/conversas'
      preLoaderRoute: typeof AppConversasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cobrancas': {
      id: '/app/cobrancas'
      path: '/cobrancas'
      fullPath: '/app/cobrancas'
      preLoaderRoute: typeof AppCobrancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avaliacoes': {
      id: '/app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/app/avaliacoes'
      preLoaderRoute: typeof AppAvaliacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automacoes': {
      id: '/app/automacoes'
      path: '/automacoes'
      fullPath: '/app/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atividade': {
      id: '/app/atividade'
      path: '/atividade'
      fullPath: '/app/atividade'
      preLoaderRoute: typeof AppAtividadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/meta-leads': {
      id: '/api/webhooks/meta-leads'
      path: '/api/webhooks/meta-leads'
      fullPath: '/api/webhooks/meta-leads'
      preLoaderRoute: typeof ApiWebhooksMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/zapi-receive': {
      id: '/api/webhooks/zapi-receive'
      path: '/api/webhooks/zapi-receive'
      fullPath: '/api/webhooks/zapi-receive'
      preLoaderRoute: typeof ApiWebhooksZapiReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/zapi-status': {
      id: '/api/webhooks/zapi-status'
      path: '/api/webhooks/zapi-status'
      fullPath: '/api/webhooks/zapi-status'
      preLoaderRoute: typeof ApiWebhooksZapiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/zapi-disconnect': {
      id: '/api/webhooks/zapi-disconnect'
      path: '/api/webhooks/zapi-disconnect'
      fullPath: '/api/webhooks/zapi-disconnect'
      preLoaderRoute: typeof ApiWebhooksZapiDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/zapi-connect': {
      id: '/api/webhooks/zapi-connect'
      path: '/api/webhooks/zapi-connect'
      fullPath: '/api/webhooks/zapi-connect'
      preLoaderRoute: typeof ApiWebhooksZapiConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/meta-messages': {
      id: '/api/webhooks/meta-messages'
      path: '/api/webhooks/meta-messages'
      fullPath: '/api/webhooks/meta-messages'
      preLoaderRoute: typeof ApiWebhooksMetaMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/meta-comments': {
      id: '/api/webhooks/meta-comments'
      path: '/api/webhooks/meta-comments'
      fullPath: '/api/webhooks/meta-comments'
      preLoaderRoute: typeof ApiWebhooksMetaCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cs-touchpoints': {
      id: '/api/cron/cs-touchpoints'
      path: '/api/cron/cs-touchpoints'
      fullPath: '/api/cron/cs-touchpoints'
      preLoaderRoute: typeof ApiCronCsTouchpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAtividadeRoute: typeof AppAtividadeRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppAvaliacoesRoute: typeof AppAvaliacoesRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppCobrancasRoute: typeof AppCobrancasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConversasRoute: typeof AppConversasRoute
  AppDiagnosticoRoute: typeof AppDiagnosticoRoute
  AppImportarRoute: typeof AppImportarRoute
  AppOportunidadesRoute: typeof AppOportunidadesRoute
  AppPacientesRoute: typeof AppPacientesRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtividadeRoute: AppAtividadeRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppAvaliacoesRoute: AppAvaliacoesRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppCobrancasRoute: AppCobrancasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConversasRoute: AppConversasRoute,
  AppDiagnosticoRoute: AppDiagnosticoRoute,
  AppImportarRoute: AppImportarRoute,
  AppOportunidadesRoute: AppOportunidadesRoute,
  AppPacientesRoute: AppPacientesRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PTokenRoute: PTokenRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiWebhooksMetaLeadsRoute: ApiWebhooksMetaLeadsRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiWebhooksZapiReceiveRoute: ApiWebhooksZapiReceiveRoute,
  ApiWebhooksZapiStatusRoute: ApiWebhooksZapiStatusRoute,
  ApiWebhooksZapiDisconnectRoute: ApiWebhooksZapiDisconnectRoute,
  ApiWebhooksZapiConnectRoute: ApiWebhooksZapiConnectRoute,
  ApiWebhooksMetaMessagesRoute: ApiWebhooksMetaMessagesRoute,
  ApiWebhooksMetaCommentsRoute: ApiWebhooksMetaCommentsRoute,
  ApiCronCsTouchpointsRoute: ApiCronCsTouchpointsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
